### ISSUE TITLE
Show the world map as background

### ISSUE THREAD

**Issue by mdislam** [osiris-indoor/mapviewer-android#1]
Hi:

I am developing an android indoor map application using the Osiris-android code. Currently, I can see only the sample map on the android application not the whole world map. 

But, I would like to see the whole world map (for example OpenStreet map) as the background and then when I will zoom in to certain location the indoor map will appear. Could you please let me know how to achieve that?

**Comment by guillefhc** [comment]
Hi

This application is an example and uses [mapsforge](http://www.mapsforge.org) for displaying  maps.

Mapsforge works with precompiled maps. The source data is taken from OpenStreetMap and converted with [Osmosis](https://github.com/mapsforge/mapsforge/blob/master/docs/Getting-Started-Map-Writer.md). [Applications](https://github.com/mapsforge/mapsforge/blob/master/docs/Mapsforge-Applications.md) that make use of Mapsforge are usually oriented to a limited map region or a country.

If you need the whole map you should consider a different component allowing to overlay a custom vectorial layer over the basemap.

**Comment by mdislam** [comment]
Hi:

Thank you for the reply.

We are implementing an indoor application where we are planning to use,
OpenStreetMap as background and Osiries for indroor map.

Our intention is as follows,
(a) Read the indoor information from Osiries server (Which is GeoJson)
(b) Fed the GeoJson to OpenStreeMap overlay manager to render it over OpenStreetMap.

We are expecting your suggestion in this regard, are we heading towards the right direction?

**Comment by guillefhc** [comment]
Hi

Sorry if I wasn't clear enough. Yes, that's the right approach. Just change
Mapsforge for another component which allows on demand download from
OpenStreetMap

Regards

2016-05-04 15:41 GMT+02:00 Md. Mesbahul Islam notifications@github.com:

**Comment by mdislam** [comment]
Hi:

Thank you for the reply. According to the suggestion, I was changing the code to support another component for on-demand downloading.

I have changed only the `MapsforgeView.java` under `com.fhc25.percepcion.osiris.mapviewer.ui.views.indoor` package. In the code, I have used `TileDownloadLayer` instead of `TileRendererLayer`.

But when I am running the app, the screen shows only floors number with white background (please refer to the attached image) 
![device-2016-05-10-111042](https://cloud.githubusercontent.com/assets/2608597/15139658/f3e77dcc-169f-11e6-9fd3-f3cb5a726382.png)

Am I missing something? or Do I need to change code somewhere else? I am sorry for bothering you with this issue.

I am also pasting the changed portion of that class in following for your convenience:

```
protected TileDownloadLayer downloadLayer;

public void setMapFile(File mapFile) {

        if (downloadLayer != null
                && mapView.getLayerManager().getLayers()
                .contains(downloadLayer)) {
            mapView.getLayerManager().getLayers()
                    .remove(downloadLayer);
            downloadLayer.onDestroy();
            downloadLayer = null;
        }

        tileCache.destroy();
        // create a tile cache of suitable size
        tileCache = AndroidUtil.createTileCache(getContext(),
                "mapcache", mapView.getModel().displayModel.getTileSize(), 1f,
                mapView.getModel().frameBufferModel.getOverdrawFactor());

        mapView.getModel().mapViewPosition.setMapPosition(new MapPosition(new LatLong(60.161068, 24.545447), (byte) 16));

        downloadLayer = new TileDownloadLayer(tileCache,
                this.mapView.getModel().mapViewPosition, OpenStreetMapMapnik.INSTANCE,
                AndroidGraphicFactory.INSTANCE);

        try {
            mapView.getLayerManager().getLayers().add(downloadLayer);

            setMapPosition(60.161068, 24.545447);
            setZoomLevel(zoom);
        } catch (Exception e) {
            Lgr.e(TAG, e);
        }
  }

public void onPause() {

        if (downloadLayer != null
                && mapView.getLayerManager().getLayers()
                .contains(downloadLayer)) {
            mapView.getLayerManager().getLayers().remove(downloadLayer);
            downloadLayer.onDestroy();
            downloadLayer = null;
        }
    }
```

**Comment by guillefhc** [comment]
I've found some things to change:

First you need to start the downloadLayer. In your code could be something like this:

```
    try {
        mapView.getLayerManager().getLayers().add(downloadLayer);
        downloadLayer.start() 
        setMapPosition(60.161068, 24.545447);
        setZoomLevel(zoom);
    } catch (Exception e) {
        Lgr.e(TAG, e);
    }
```

second, you have to change a line on ui/overlays/mapsforge/MapsforgeDisplayer.java 
    @Override
    public void clear() {

```
    Log.i(TAG, "clear");
    java.util.Collection<Layer> removeElementsList = new ArrayList<Layer>();

    for (Layer layer : mapView.getLayerManager().getLayers()) {

        if (!(layer instanceof TileRendererLayer || layer instanceof TileDownloadLayer)) {
            removeElementsList.add(layer);
        }
    }

    for (Layer layer : removeElementsList) {
        mapView.getLayerManager().getLayers().remove(layer);
    }
}
```

**Comment by mdislam** [comment]
Hi:

Thank you for the reply.

I have changed the code according to your suggestion but unfortunately the result is same as before (white background, no map). I have forked the repository and pushed a new branch with my changes. I would be grateful if you could look into and try to run the code on your machine and see the output. Further suggestions are highly appreciated.

Please note that, I was using the aachen sample map.

The branch link:
https://github.com/mdislam/mapviewer-android/tree/osm-background

**Comment by NimaaZx** [comment]
@mdislam hello. Did you get the result you wanted? Overlay your map on world map? I have seen a lot of sdk do that but they are not free. I think there is a big challenge for indoor map. If you have an experience i would be grateful to share me. Thanks
